/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
    '../../packages/ui/src/**/*.{js,ts,jsx,tsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        error: '#ffb4ab',
        'surface-variant': '#2d3449',
        'outline-variant': '#3c4947',
        'on-secondary-fixed': '#23005c',
        'secondary-container': '#571bc1',
        'primary-container': '#14b8a6',
        'on-tertiary-fixed': '#002113',
        'on-primary-fixed-variant': '#005048',
        'on-primary': '#003731',
        'surface-container-high': '#222a3d',
        primary: '#4fdbc8',
        'secondary-fixed': '#e9ddff',
        'inverse-on-surface': '#283044',
        'tertiary-container': '#16bb83',
        'surface-tint': '#4fdbc8',
        'primary-fixed-dim': '#4fdbc8',
        surface: '#0b1326',
        outline: '#859490',
        secondary: '#d0bcff',
        'tertiary-fixed': '#6ffbbe',
        'on-error-container': '#ffdad6',
        background: '#0b1326',
        'secondary-fixed-dim': '#d0bcff',
        'surface-container-lowest': '#060e20',
        'on-background': '#dae2fd',
        'on-secondary-container': '#c4abff',
        'error-container': '#93000a',
        'on-surface-variant': '#bbcac6',
        'on-surface': '#dae2fd',
        'surface-bright': '#31394d',
        'on-secondary-fixed-variant': '#5516be',
        'on-primary-container': '#00423b',
        'on-tertiary-container': '#00442c',
        'surface-dim': '#0b1326',
        'primary-fixed': '#71f8e4',
        'on-tertiary-fixed-variant': '#005236',
        'on-secondary': '#3c0091',
        'surface-container': '#171f33',
        'inverse-primary': '#006b5f',
        'on-primary-fixed': '#00201c',
        'on-error': '#690005',
        'on-tertiary': '#003824',
        'inverse-surface': '#dae2fd',
        'tertiary-fixed-dim': '#4edea3',
        'surface-container-low': '#131b2e',
        tertiary: '#4edea3',
        'surface-container-highest': '#2d3449',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        base: '4px',
        sm: '12px',
        xxl: '48px',
        lg: '24px',
        gutter: '24px',
        md: '16px',
        'container-max': '1280px',
        xl: '32px',
        xs: '8px',
      },
      fontFamily: {
        'label-sm': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Inter', 'sans-serif'],
        display: ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'label-sm': ['12px', { lineHeight: '1', fontWeight: '500' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'headline-lg': [
          '32px',
          { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '700' },
        ],
        'label-md': [
          '14px',
          { lineHeight: '1', letterSpacing: '0.02em', fontWeight: '600' },
        ],
        'body-sm': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'headline-lg-mobile': ['24px', { lineHeight: '1.2', fontWeight: '700' }],
        display: [
          '48px',
          { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' },
        ],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};
